swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Get Account informations
      description:
        This call returns all payment accounts that are relevant regarding of
        whom is connected
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/AccountsInfos'
        '401':
          description: Unauthorized, authentication failure.
        '403':
          description: Forbidden
        '404':
          description: Not found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
  /user/accounts/{accountID}:
    get:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Get monthly transaction history
      description: This call returns transactions history for a month for an account
      parameters:
        - in: path
          name: accountID
          description: unique account ID
          required: true
          type: string
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized, authentication failure.
        '403':
          description: Forbidden
        '404':
          description: Not found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
  /user/accounts/{accountID}/{transactionID}/{item}:
    put:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Transaction category or note update
      description: 
        This call allows the user to add or modify a category or a note for a given
        transaction
      parameters:
        - in: body
          name: body
          description: Update transaction attribute
          required: true
          schema:
            $ref: '#/definitions/ModifyCat'
        - in: path
          name: accountID
          description: unique account ID
          required: true
          type: string
        - in: path
          name: transactionID
          description: unique transaction ID
          required: true
          type: string
        - in: path
          name: item
          description: note or category
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Changes saved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized, authentication failure.
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
          
          

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: array
    items:
      type: object
      properties:
        currency:
          type: string
        date:
          type: string
          format: date
        transactionID:
          type: string
        desc:
          type: string
        amount:
          type: number
        balance:
          type: number
        transaction type:
          type: string
        category:
          type: string
        note:
          type: string
  AccountsInfos:
    type: array
    items:
      type: object
      properties:
        accountID:
          type: string
        accountName:
          type: string
        currency:
          type: string
        accountBalance:
          type: number
        nbrTransaction:
          type: number
        AccountHistoric:
          type: array
          items:
            type: object
            properties:
              transactionID:
                type: string
              date:
                type: string
                format: date
              desc:
                type: string
              amount:
                type: number
              balance:
                type: number
              transaction type:
                type: string
              category:
                type: string
              note:
                type: string
  ModifyCat:
    type: object
    properties:
      item:
        type: string

