swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
          
  /user/accounts/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Get monthly transaction history
      description: This call returns transactions history for a month for an account
      parameters:
        - in: path
          name: accountId
          description: unique account ID
          required: true
          type: string
      responses:
        '200':
          description: Historic retrieved successully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized, authentication failure.
        '403':
          description: Forbidden
        '404':
          description: Not found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
          
  /user/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Get transaction details
      description: This call returns transactions details
      parameters:
        - in: path
          name: transactionId
          description: unique transaction Id
          required: true
          type: string
      responses:
        '200':
          description: Historic retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetail'
        '401':
          description: Unauthorized, authentication failure.
        '403':
          description: Forbidden
        '404':
          description: Not found
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - Account
      summary: Transaction category or note update
      description: 
        This call allows the user to add or modify a category or a note for a given
        transaction
      parameters:
        - in: body
          name: body
          description: Update transaction attribute
          required: true
          schema:
            $ref: '#/definitions/ModifyCat'
        - in: path
          name: transactionId
          description: unique transaction Id
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Changes saved successfully
          schema:
            $ref: '#/definitions/NewTransactionInfos'
        '401':
          description: Unauthorized, authentication failure.
        '408':
          description: Request Timeout
        '500':
          description: Internal Server Error
          
          

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: array
    items:
      type: object
      properties:
        currency:
          type: string
        date:
          type: string
          format: date
        transactionID:
          type: string
        desc:
          type: string
        amount:
          type: number
        balance:
          type: number
          
  TransactionDetail:
      type: object
      properties:
        currency:
          type: string
        date:
          type: string
          format: date
        transactionID:
          type: string
        desc:
          type: string
        amount:
          type: number
        balance:
          type: number
        Transaction type:
          type: string
        Category :
          type: string
        Note:
          type: string

  NewTransactionInfos:
      type: object
      properties:
        currency:
          type: string
        date:
          type: string
          format: date
        transactionID:
          type: string
        desc:
          type: string
        amount:
          type: number
        balance:
          type: number
        Transaction type:
          type: string
        Category :
          type: string
        Note:
          type: string
        
  ModifyCat:
    type: object
    properties:
        Category :
          type: string
        Note:
          type: string

